### ISSUE TITLE
Convert CSV to JSON

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-4-rest-api-hackathon-16bites#2]
```[tasklist]
### Tasks
- [x] Download Pokemon CSV from kaggle
- [x] Import into repo
- [x] convert datatypes into JSON for API functionality
```

**Comment by BeardedGrinn** [comment]
Found website to convert CSV to JSON
