### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-4-rest-api-hackathon-16bites#3]
```[tasklist]
### Tasks
- [x] Create readme.md
- [x] Add information on what the API does
- [x] Add instruction on how to use API
- [x] Update instructions once endpoints etc are finalised
```
